/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fruitbasket.app;

import java.util.ArrayList;

public class App {

    public void displayItemList(ArrayList<Item> itemList){
        for(Item item : itemList){
            System.out.println("Name: "+item.getFruitName()+" Size: "+item.getSize());
        }
    }

    public static void main(String[] args) {
       oldBasket oldbasket = new oldBasket();
       newBasket newbasket = new newBasket();


        ArrayList<Item> oldfruit = new ArrayList<>();

        oldfruit.add(new Item("apple","red",3));
        oldfruit.add(new Item("orange","orange",2));
        oldfruit.add(new Item("grape","green",1));
        oldfruit.add(new Item("cherry","red",1));
        oldfruit.add(new Item("pomegranate","pink",3));
        oldfruit.add(new Item("guava","green",2));

        oldbasket.setItems(oldfruit);
        newbasket.setoldBasket(oldbasket);
        newbasket.sortFruits();



        App sc = new App();
        System.out.println("  Fruits in top-bowl");
        sc.displayItemList(newbasket.getFruitsSize1());
        System.out.println("  Fruits in middle-bowl");
        sc.displayItemList(newbasket.getFruitsSize2());
        System.out.println("  Fruits in bottom-bowl");
        sc.displayItemList(newbasket.getFruitsSize3());



    }
}
